### ISSUE TITLE
URLの入力

### ISSUE THREAD

**Issue by dala00** [kokushin/makepost-issue#3]
## 概要

URLの入力欄が無い

## 提案内容

こういうサービスはURLの入力が当たり前になっているため、URLを入力していた気になっていましたが、入力欄が無いため実は入力しておらず、リンクされていないということにようやく気づきました。他にもURL入力されてない方が何人かいるようです。

URLは入力欄を追加し、各サービス名のタイトルやURL表示等からリンクされていると自然のような気がします。

**Comment by kokushin** [comment]
@dala00 さん、こんにちは。
ご提案ありがとうございます！

現状、プロジェクト説明内にURLを含めることができますが、
仰る通り、別でURL欄を設けたほうが分かりやすくなりそうですね。
こちら対応を進めさせて頂きます！

**Comment by kokushin** [comment]
こちら対応いたしました。
ご提案、ありがとうございました！
https://www.makepost.net/projects/3?story=36
